### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by juliofortunato** [yeyushengfan258/Citrus-icon-theme#1]
Great job with these icons, loved it!

Is it possible to add icons for Discord and Visual Studio Code, please?

**Comment by yeyushengfan258** [comment]
Well,&nbsp;at&nbsp;next week's&nbsp;updated&nbsp;week,&nbsp;I&nbsp;will&nbsp;add



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Júlio Fortunato"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 晚上10:20
收件人:&nbsp;"yeyushengfan258/Citrus-icon-theme"<Citrus-icon-theme@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yeyushengfan258/Citrus-icon-theme] New icons (#1)




Great job with these icons, loved it!
 
Is it possible to add icons for Discord and Visual Studio Code, please?

**Comment by yeyushengfan258** [comment]
> 这些图标非常棒，喜欢它！
> 
> 是否可以为Discord和Visual Studio Code添加图标？

好，下次更新我再添加吧。

**Comment by yeyushengfan258** [comment]
> 这些图标非常棒，喜欢它！
> 
> 是否可以为Discord和Visual Studio Code添加图标？

OK
